export const getCurrencySymbol = (currencyCode: string): string => {
  const symbols: { [key: string]: string } = {
    'USD': '$',
    'EUR': '€',
    'JPY': '¥',
    'GBP': '£',
    'CHF': 'CHF',
    'CAD': 'C$',
    'AUD': 'A$',
    'NZD': 'NZ$',
    'SEK': 'kr',
    'NOK': 'kr',
    'DKK': 'kr',
    'PLN': 'zł',
    'CZK': 'Kč',
    'HUF': 'Ft',
    'RUB': '₽',
    'CNY': '¥',
    'KRW': '₩',
    'SGD': 'S$',
    'HKD': 'HK$',
    'INR': '₹',
    'BRL': 'R$',
    'MXN': '$',
    'ZAR': 'R',
    'TRY': '₺',
    'THB': '฿',
    'IDR': 'Rp',
    'PHP': '₱',
    'MYR': 'RM',
    'AED': 'د.إ',
    'SAR': '﷼',
    'QAR': '﷼',
    'KWD': 'د.ك',
    'BHD': 'د.ب',
    'OMR': '﷼',
    'JOD': 'د.ا',
    'LBP': 'ل.ل',
    'EGP': '£',
    'ILS': '₪',
    'PKR': '₨',
    'BDT': '৳',
    'LKR': '₨',
    'MMK': 'K',
    'KHR': '៛',
    'LAK': '₭',
    'VND': '₫',
    'UAH': '₴',
    'BGN': 'лв',
    'RON': 'lei',
    'HRK': 'kn',
    'RSD': 'дин',
    'MKD': 'ден',
    'BAM': 'КМ',
    'ALL': 'L',
    'ISK': 'kr',
    'UYU': '$U',
    'ARS': '$',
    'CLP': '$',
    'COP': '$',
    'PEN': 'S/',
    'BOB': 'Bs',
    'VES': 'Bs.S',
    'PYG': '₲',
    'GTQ': 'Q',
    'HNL': 'L',
    'NIO': 'C$',
    'CRC': '₡',
    'PAB': 'B/.',
    'DOP': 'RD$',
    'JMD': 'J$',
    'TTD': 'TT$',
    'BBD': 'Bds$',
    'XCD': 'EC$',
    'AWG': 'ƒ',
    'BZD': 'BZ$',
    'GYD': 'G$',
    'SRD': 'SRD',
    'FJD': 'FJ$',
    'PGK': 'K',
    'SBD': 'SI$',
    'VUV': 'Vt',
    'WST': 'WS$',
    'TOP': 'T$',
    'BTN': 'Nu.',
    'MVR': 'Rf',
    'SCR': '₨',
    'MUR': '₨',
    'KMF': 'CF',
    'DJF': 'Fdj',
    'ETB': 'Br',
    'KES': 'KSh',
    'TZS': 'TSh',
    'UGX': 'USh',
    'RWF': 'RF',
    'BIF': 'FBu',
    'MWK': 'MK',
    'ZMW': 'ZK',
    'BWP': 'P',
    'SZL': 'E',
    'LSL': 'L',
    'NAD': 'N$',
    'AOA': 'Kz',
    'MZN': 'MT',
    'MGA': 'Ar',
    'CDF': 'FC',
    'GMD': 'D',
    'GNF': 'FG',
    'LRD': 'L$',
    'SLL': 'Le',
    'GHS': '₵',
    'NGN': '₦',
    'XOF': 'CFA',
    'XAF': 'FCFA',
    'STN': 'Db',
    'CVE': '$',
    'GIP': '£',
    'FKP': '£',
    'SHP': '£',
    'TND': 'د.ت',
    'DZD': 'د.ج',
    'MAD': 'د.م.',
    'XPF': '₣',
    'AMD': '֏',
    'AZN': '₼',
    'GEL': '₾',
    'KZT': '₸',
    'KGS': 'лв',
    'TJS': 'SM',
    'TMT': 'T',
    'UZS': 'лв',
    'AFN': '؋',
    'IRR': '﷼',
    'IQD': 'ع.د',
    'SYP': '£',
    'YER': '﷼',
    'ESP': '₧', // Spanish Peseta (historical)
    'ITL': '₤', // Italian Lira (historical)
    'DEM': 'DM', // German Mark (historical)
    'FRF': '₣', // French Franc (historical)
    'NLG': 'ƒ', // Dutch Guilder (historical)
    'BEF': '₣', // Belgian Franc (historical)
    'ATS': 'S', // Austrian Schilling (historical)
    'FIM': 'mk', // Finnish Markka (historical)
    'IEP': '£', // Irish Pound (historical)
    'PTE': '₣', // Portuguese Escudo (historical)
    'GRD': '₯', // Greek Drachma (historical)
    'LUF': '₣', // Luxembourg Franc (historical)
    'SIT': 'SIT', // Slovenian Tolar (historical)
    'SKK': 'Sk', // Slovak Koruna (historical)
    'CYP': '£', // Cypriot Pound (historical)
    'MTL': '₤', // Maltese Lira (historical)
    'LVL': 'Ls', // Latvian Lats (historical)
    'LTL': 'Lt', // Lithuanian Litas (historical)
    'EEK': 'kr', // Estonian Kroon (historical)
  };

  return symbols[currencyCode] || currencyCode;
};